Add functions for replace child and replace clause
RedisGraph/libcypher-parser pull request #11
Opened 2022-02-04 19:50 UTC by jeffreylovitz

Adds the new functions `cypher_astnode_set_child` and `cypher_ast_query_set_clause`, as well as fixing several bugs in the AST clone logic.

2022-02-06 07:18 UTC, swilly22 requested changes
Looking good, I have a few questions

2022-02-06 07:18 UTC, swilly22 commented on lib/src/ast.c
> +    free(children);
was it leaking ? when do we call `cypher_ast_clone` ?

2022-02-06 07:18 UTC, swilly22 commented on lib/src/ast_query.c
> +    node->clauses[index] = clause;
What guarantees do we have that `node->clauses[index]` is allocated, in addition are we overwriting anything at `node->clauses[index]` ?

2022-02-06 07:18 UTC, swilly22 commented on lib/src/ast_return.c
> +    cypher_astnode_t *limit = (node->limit == NULL) ? NULL :
what are the side effects of these faulty conditions ?

2022-02-06 07:18 UTC, swilly22 commented on lib/src/ast_with.c
> +    cypher_astnode_t *limit = (node->limit == NULL) ? NULL :
what are the side effects of these faulty conditions ?

2022-02-06 07:18 UTC, swilly22 commented on lib/src/astnode.h
>      while (i < node->nchildren && node->children[i] != child)
Before the fix, isn't this an infinity loop ? for `child` which is different than `node->children[0]`

2022-02-06 07:18 UTC, swilly22 commented on lib/src/cypher-parser.h.in
> +
Similar to `cypher_astnode_set_child` which seems generic why do we need this function,
Isn't it a specific version of the former?

2022-02-07 17:11 UTC, jeffreylovitz commented on lib/src/ast.c
> +    free(children);
Previously, we never called `cypher_ast_clone` (and I'm guessing no one else did either, given how severe some of the bugs in its logic are). This was leaking before, yes.

2022-02-07 17:11 UTC, jeffreylovitz commented on lib/src/ast_query.c
> +    node->clauses[index] = clause;
No guarantees, though I can add an assertion.

We are overwriting data in our use case. Currently we are freeing the replaced node explicitly, though I can place that free here instead if preferred.

2022-02-07 17:11 UTC, jeffreylovitz commented on lib/src/astnode.h
>      while (i < node->nchildren && node->children[i] != child)
Correct! Only the `cypher_ast_clone` logic uses this function, which makes me think it was previously untested.

2022-02-10 20:47 UTC, merged