negative params
RedisGraph/libcypher-parser pull request #3
Opened 2020-09-10 12:01 UTC by DvirDukhan

2020-09-10 12:45 UTC, swilly22 requested changes

2020-09-10 12:45 UTC, swilly22 commented on lib/test/check_statement.c
> +    result = cypher_parse("CYPHER pos_int_val=1 neg_int_val=-1 pos_float_val=2.3 neg_float_val=-2.3 true_val=true false_val=false null_val=NULL string_val='str' arr_val=[1,2,3] map_val={ int_val:1, f
Please add a check for positive numbers specified with leading '+' sign, e.g. `+1`

2020-09-10 12:45 UTC, swilly22 commented on lib/src/parser.leg
> +    | _atom
What does `_atom` stands for?

2020-09-10 13:12 UTC, DvirDukhan commented on lib/src/parser.leg
> +    | _atom
```
_atom =
      _block_start_ PREFIX-OP - r:_prec_expression _block_end_
                                       { $$ = unary_operator(op_pop(), r); }
    | atom
```

2020-09-12 08:09 UTC, swilly22 approved these changes

2020-09-12 08:09 UTC, merged